### ISSUE TITLE
Confused about the Self-Processing prediction results

### ISSUE THREAD

**Issue by NRX-044** [zjlab-BioGene/CHOOSER#1]
I have tried running `03_Cas12_SelfProcessing.ipynb` using the proteins from supplementary data 7 of the related paper. The prediction of Cas12a seems fine but only 2 out of 11 suspected Casλ have been correctly predicted as capable of self processing crRNA and none of the suspected Cas12m have been predicted correctly. The prediction results seems quite different from the scores presented in supplementary data 7.
<img width="163" alt="Pred_results" src="https://github.com/user-attachments/assets/b13b113c-a8ed-4edf-a407-1c4058ae73fb" />

**Info for reproduction**

**Code**
- [x] Official notebook on Google Colab : https://colab.research.google.com/drive/1D5_Qffq-EUZYQk_tTKMftCv9wvxSh2Kz?usp=sharing
- [ ] My own modified script

**Tasks**
- [x] Supplementary data 7 from https://doi.org/10.1038/s41467-024-54365-0
- [ ] My own proteins data

**Parameters**

- model: CLS_best
- emb_dim: 1280 
- seed: 42

**Comment by zjlab-BioGene** [comment]
> I have tried running `03_Cas12_SelfProcessing.ipynb` using the proteins from supplementary data 7 of the related paper. The prediction of Cas12a seems fine but only 2 out of 11 suspected Casλ have been correctly predicted as capable of self processing crRNA and none of the suspected Cas12m have been predicted correctly. The prediction results seems quite different from the scores presented in supplementary data 7. <img alt="Pred_results" width="163" src="https://private-user-images.githubusercontent.com/81204013/395441828-b13b113c-a8ed-4edf-a407-1c4058ae73fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTkyMDksIm5iZiI6MTczNDMxODkwOSwicGF0aCI6Ii84MTIwNDAxMy8zOTU0NDE4MjgtYjEzYjExM2MtYThlZC00ZWRmLWE0MDctMWM0MDU4YWU3M2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAzMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YWYwZDVjM2VlODliZjc5Yjc1YmIyZjg3MjhkMzFlOGYyZGQ5ODU5ZWZkOTVlOTQzNmQxMGQxNGFiN2M3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EyHXGZ0b8QvcuckDY17tVITBZ6KDLYBbx4bBNqqfZbA">
> 
> **Info for reproduction**
> 
> **Code**
> 
> * [x]  Official notebook on Google Colab : https://colab.research.google.com/drive/1D5_Qffq-EUZYQk_tTKMftCv9wvxSh2Kz?usp=sharing
> * [ ]  My own modified script
> 
> **Tasks**
> 
> * [x]  Supplementary data 7 from https://doi.org/10.1038/s41467-024-54365-0
> * [ ]  My own proteins data
> 
> **Parameters**
> 
> * model: CLS_best
> * emb_dim: 1280
> * seed: 42

Thank you for bringing this to my attention!

I truly appreciate you taking the time to test the code and provide feedback. After reviewing the notebook you referenced, 03_Cas12_SelfProcessing.ipynb, I identified a bug in the implementation, which likely led to the discrepancies you observed between the prediction results and the scores presented in Supplementary Data 7.

The issue has now been resolved. Specifically, in our paper, the input to the 'CLS_best' model should be the 33rd layer embedding of 'facebook/esm2_t33_650M_UR50D', not the 10th layer, as was incorrectly implemented in the original notebook.

The updated version of the notebook has been uploaded to the repository. Please pull the latest changes or download the updated file to rerun your analysis. The new results should align with the expected outcomes as presented in the paper.

If you encounter any further issues or if the results remain inconsistent, please don’t hesitate to reach out. Your feedback is invaluable, and I’m happy to assist further to ensure everything works as expected.

Thank you once again for your detailed feedback and for helping improve the code!

Best regards,
Wenhui Li
liwh@tongji.edu.cn

Suppl. Data 7 Fasta: https://drive.google.com/file/d/1PrqUt8h4o81xwGM2pGjlpL8IAa3PSin2/view?usp=sharing
Colab notebook: https://colab.research.google.com/drive/1D5_Qffq-EUZYQk_tTKMftCv9wvxSh2Kz?usp=sharing

<img width="284" alt="image" src="https://github.com/user-attachments/assets/8bf419c7-c231-4273-8b4c-cd1a62224d35" />
